server:
  port: ${vcap.application.port:9000}
logging:
  level:
    org: WARN
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

quartz:
  enabled: true

queue.job.frequency: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.vqserver-eureka.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80

spring:
  profiles: cloud
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vq
    username: root
    password :

  jackson.serialization.indent_output: true
  oauth2.resource.userInfoUri: ${vcap.services.vqserver-auth.credentials.uri:http://localhost:9999}/uaa/user
