server:
  port: ${vcap.application.port:9999}
  contextPath: /uaa

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.vqserver-eureka.credentials.uri:http://127.0.0.1:8761}/eureka/
    instance:
      hostname: ${APPLICATION_DOMAIN}
      nonSecurePort: 80

security:
  user:
    password: password

logging:
  level:
    org: WARN
#    springframework:
#      security: DEBUG


spring:
  profiles: cloud
  jackson.serialization.indent_output: true