security:
  user:
    password: password
zuul:
  proxy:
    mapping: /resource/**
    addProxyHeaders: true
    route:
      vqserver-endpoint: /
  routes:
    user:
      path: /user/**
      url: ${vcap.services.vqserver-auth.credentials.uri:http://localhost:9999}/uaa/user

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.vqserver-eureka.credentials.uri:http://127.0.0.1:8761}/eureka/

logging:
  level:
    org: WARN
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG

spring:
  profiles: cloud
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: ${vcap.services.vqserver-auth.credentials.uri:http://localhost:9999}/uaa/oauth/token
      userAuthorizationUri: ${vcap.services.vqserver-auth.credentials.uri:http://localhost:9999}/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: ${vcap.services.vqserver-auth.credentials.uri:http://localhost:9999}/uaa/user
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80